### ISSUE TITLE
Filename encoding issue

### ISSUE THREAD

**Issue by glennjones** [tessel/sdcard#17]
Hi, 

I am trying out the example sd-card code and the file writes to the sd-card, but the file name is encoded incorrectly. This means I can not read it back again and get the error.

``/app/microsd.js:19: attempt to index local 'data' (a nil value)``

**Comment by natevw** [comment]
Tessel now has built-in support for the utf16le buffer encoding (https://github.com/tessel/runtime/pull/645) and so this issue is likely resolved. (IIRC struct-fu also got an interim fix for this.) Thanks for your original report!
