### ISSUE TITLE
Saving image from camera is getting slower with each new image

### ISSUE THREAD

**Issue by brankosekulic** [tessel/sdcard#20]
Here is the code

```
function takePic(){

    var t1, t2;

    camera.takePicture(function(err, image) {

        if (err) {
            console.log('error taking image', err);
        } else {
            var name = 'picture-' + Math.floor(Date.now()*1000) + '.jpg';

            t1 = new Date().getTime();

            sdFileSys.writeFile(name, image, function(err) {                

                t2 = new Date().getTime();
                console.log(t2 - t1);
                takePic();
            });
        }
    });
}
```

Here are times I received from first to last:

[ 62599, 75760, 96929, 117893, 145398, 165542, 192784, 217749, 251097, 272029, 306743, 372493, 379974, 403448, 420971, 460497, 507298, ... ]

**Comment by brankosekulic** [comment]
It's working better if I fetch the fileSystem again each time before saving new image:

```
function takePic(){

    var t1, t2;

    camera.takePicture(function(err, image) {

        if (err) {
            console.log('error taking image', err);
        } else {
            var name = 'picture-' + Math.floor(Date.now()*1000) + '.jpg';

            t1 = new Date().getTime();

            sdcard.getFilesystems(function(err, fss) {

                sdFileSys = fss[0];
                sdFileSys.writeFile(name, image, function(err) {                

                    t2 = new Date().getTime();
                    console.log(t2 - t1);
                    takePic();
                });
            });
        }
    });
}
```

**Comment by natevw** [comment]
@brankosekulic How often is `takePic` called? I'm assuming you have it on some interval?

**Comment by brankosekulic** [comment]
@natevw there is no interval, tekePic() is called when writing of the previous image is done (inside writeFile callback) 

```
sdFileSys.writeFile(name, image, function(err) {                
    t2 = new Date().getTime();
    console.log(t2 - t1);
    takePic();
});
```

Saving picture takes about 75 seconds, so that's the interval of calling takePic function

**Comment by natevw** [comment]
> which also implies there are no parallel writes

You read my mind ;-) Thanks for pointing out the recursive bit I missed, hope to dive into this later today.

**Comment by natevw** [comment]
I am able to reproduce this (or something like this?) at the fatfs level, and have filed: https://github.com/natevw/fatfs/issues/17

I did not see a significant benefit to "starting fresh" with a new filesystem, in my testing I restarted the whole script and it picked up about as slow as it was before. Have you been using your workaround for a while now, and it does keep things fast? If so, maybe these are somehow different things then?

**Comment by brankosekulic** [comment]
Your example works for me as you described, but my workaround for camera images still keep things fast :) Probably that's the same issue.

**Comment by brankosekulic** [comment]
Here is my original script which causing significant time increase:

```
require('tesselate') ({
  modules: {
    A: ['sdcard', 'sdcard'],
    B: ['camera-vc0706', 'camera']
  }
}, function (tessel, modules) {

    var sdcard = modules.sdcard,
        camera = modules.camera;

    var sdFileSys,
        times = [];

    function takePic(){

        var name, t1, t2;

        camera.takePicture(function(err, image) {

            name = 'picture-' + Date.now() + '.jpg';
            t1 = new Date().getTime();

            sdFileSys.writeFile(name, image, function(err) {

                t2 = new Date().getTime();
                times.push(t2 - t1);
                console.log(times);

                takePic();
            });
        });
    }

    sdcard.getFilesystems(function(err, fss) {

        sdFileSys = fss[0];
        takePic();
    });
});
```

**Comment by natevw** [comment]
One important thing that may explain the difference between my tests and yours — the sdcard module had not been updated to a fatfs version with tons of caching fixes/improvements! I've published a fix for that. Can `npm install` again and try your project with the latest (sdcard@0.8.6 should include fatfs@0.10.2)?

Note that there still might be some initial slowdown, but it seems to stabilize at an improved point for me after a little while. Not exactly sure what's causing that but you can follow along at https://github.com/natevw/fatfs/issues/17 if interested.

**Comment by brankosekulic** [comment]
@natevw sorry for delayed answer, this works excellent, there is no time increase with new images, and also work much more faster.

Here are times with sdcard@0.8.6 (without fetching file system each time saving new image):
[ 20574, 20224, 20088, 20287, 19686, 19769, 20728, ... ]

Thanks!

**Comment by brankosekulic** [comment]
Actually, there is still some time increase, but still better then it was before:

[ 20574, 20224, 20088, 20287, 19686, 19769, 20728, 21554, 21881, 22128, 20846, 21935, 22425, 22887, 22309, 22050, 22605, 22739, 22864, 23613, 23120, 23199, 23363, 23515, 24290, 24347, 23891, 23944, 24097, 24976, 24327, 25870, 24546, 25081, 24795, 25735, 25267, 26632, 25384, 25432, 26399, 25708, 26475, 27418, 26130, 26131, ... ]

**Comment by natevw** [comment]
Great to hear! I'm going to assume this slowdown is just the growing amount of files (which takes surprisingly log time to process even with "new" LuaJIT runtime released a while ago). Closing this but leaving https://github.com/natevw/fatfs/issues/17 open for future investigation.

**Comment by brankosekulic** [comment]
@natevw I just noticed that this doesn't works, performances are good, but image is not saved completly - third part fro the bottom is missing:

http://postimg.org/image/8edmqokwr/ against http://postimg.org/image/46iuhxjh7/

**Comment by brankosekulic** [comment]
Opened separate case for this:
https://github.com/tessel/sdcard/issues/21
