### ISSUE TITLE
Part of image is missing while saving to sdcard

### ISSUE THREAD

**Issue by brankosekulic** [tessel/sdcard#21]
This is probably caused by switching to new version of fatfs:

version 0.8.6

![picture-1426373149481](https://cloud.githubusercontent.com/assets/810592/6653981/bf9bf218-caa7-11e4-8d92-4daca00bee26.jpg)

version 0.8.5
![picture-1426374203318](https://cloud.githubusercontent.com/assets/810592/6653973/8215de5e-caa7-11e4-8e9a-e6609e63c57e.jpg)

**Comment by brankosekulic** [comment]
This is also the case with any other file type

**Comment by johnnyman727** [comment]
@natevw may be able to help out here.

**Comment by natevw** [comment]
Oy, this doesn't seem good. Have you been able to debug any further @brankosekulic and/or made sure it's not just a bad card?

I wonder if this reliably happens whenever you write a certain file size (regardless of content) or just something that happens from time to time but usually is okay? It's interesting that (unless Github did some of its own processing to your attachement) that it's not cut off exactly at a 512-byte boundary or anything like that.

**Comment by brankosekulic** [comment]
@natevw card is good, it saves whole file with version 8.0.5

**Comment by natevw** [comment]
I am able to reproduce this by putting your good image above into a folder with test project and using this script to copy to card:


```
var tessel = require('tessel'),
    builtin_fs = require('fs'),
    sdlib = require("./");

builtin_fs.readFile("./sdcard-issues-21-complete.jpg", function (e,d) {
  if (e) throw e;
  else console.log("Opened file", d.length, "bytes");
  
  sdlib.use(tessel.port['A'], {getFilesystems:true}, function (e,arr) {
      if (e) throw e;
      else card_fs = arr[0];
      console.log("Got filesystem.");
      card_fs.writeFile("test-issue-21.jpg", d, function (e) {
          if (e) throw e;
          else console.log("Wrote file.");
      });
  });
});
```

**Comment by natevw** [comment]
This is due to https://github.com/tessel/runtime/issues/721

**Comment by natevw** [comment]
…and https://github.com/tessel/runtime/issues/722

**Comment by natevw** [comment]
I've worked around the runtime/firmware issues and with sdcard@0.8.7 I am able to save files over 4KB again.
