### ISSUE TITLE
Error: Invalid volume signature!

### ISSUE THREAD

**Issue by yetzt** [tessel/sdcard#23]
hi. when trying to use my sd card, the script dies with `Error: Invalid volume signature!`. i peeked into the code, the first sector ist just full with `0xFF`s. after fiddlign for a bit, i figured the card type detection misses out my card to expect the block number and not the byte offset as address, because when i replace the `var addr = (cardType === 'SDv2+block') ? i : i * BLOCK_SIZE;` with `var addr = i;`, in `readBlock()`, everything works. what information on my card do you need to adjust this detection thingie?

**Comment by yetzt** [comment]
the output of 'READ_OCR' is `0xc0ff8000`

**Comment by yetzt** [comment]
after reading into all the sdcard spec (most weird read all week), there seemed to be nothing wrong with the detection, but `cardType` was undefined in all the read and write methods. that's simply because `cardType` was defined in `getCardReady` and therefore out of scope for them. 

would you please be so kind and merge, so i can move on with building my tessel-driven space lazer?

**Comment by johnnyman727** [comment]
@yetzt thanks for the contribution! It's always great to see folks who aren't afraid to dive into the spec.

@natevw (the original author) can you take a look at this?

**Comment by natevw** [comment]
@yetzt Great debugging, glad you figured it out! Your fix should be on npm as `sdcard@0.8.8`. Thanks again :+1:
