### ISSUE TITLE
Not T2 compatible

### ISSUE THREAD

**Issue by dudleyjosh** [tessel/sdcard#27]
It looks like this module still makes a synchronous `pin.read()` [L196](https://github.com/tessel/sdcard/blob/master/index.js#L196) so I am assuming it has not been updated for use with Tessel 2?

**Comment by johnnyman727** [comment]
Frankly, it's probably a ton of work for very little pay off. USB flash drives are ubiquitous, cheap, reliable, and work well on T2.

**Comment by dudleyjosh** [comment]
That is what I assumed, I just happened to run into it today because I was attempting to test the `change`, `rise` and `fall` code changes I am working on with all of the modules I had available.

**Comment by rwaldron** [comment]
Is this called out in the readme? If not, then it should be
