### ISSUE TITLE
Maintainer self-nomination

### ISSUE THREAD

**Issue by natevw** [tessel/sdcard#30]
I would be willing to officially "maintain" this library, because I wrote a lot of it and it makes me sad to see the UNMAINTAINED note on the homepage! Keeping up with pi-spi and fatfs feedback hasn't proven too burdensome and I'm guessing there won't be too much upkeep here either.

/cc @tessel/maintainers

**Comment by Frijol** [comment]
Thanks @natevw! Do you need any permissions you don't already have?

**Comment by natevw** [comment]
@Frijol Oh, heh… I see now I am already still an admin on this repo. So that part should be good.

Any objections to me transitioning this repo to live under /natevw alongside fatfs? I believe GH will redirect this URL there so any links in old docs shouldn't break. Either way is fine though.

**Comment by Frijol** [comment]
it's ok by me.. @HipsterBrown @tcr @rwaldron any objections ^?

(I'd say that if they don't respond within 2 weeks you're good to go.)

**Comment by HipsterBrown** [comment]
Sounds good to me. 🙌

**Comment by natevw** [comment]
Done, thanks!
